# Generated by Django 4.2.30 on 2026-09-12 03:00

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('conversion_ratio', models.DecimalField(decimal_places=4, max_digits=8)),
                ('agreed_loss_rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('signed_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ContractPriceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('effective_from', models.DateField()),
                ('note', models.CharField(blank=True, max_length=128)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_versions', to='core.contract')),
            ],
            options={
                'ordering': ['-effective_from'],
                'unique_together': {('contract', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('planned_qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('penalty_rate_per_day', models.DecimalField(decimal_places=4, max_digits=16)),
                ('penalty_cap', models.DecimalField(decimal_places=4, max_digits=16)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.contract')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('contract', 'due_date')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('RAW', '原材料'), ('PRODUCT', '加工成品')], max_length=8)),
                ('unit', models.CharField(max_length=16)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('issued_qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('issued_at', models.DateField()),
                ('locked', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_receipt_no', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('NORMAL', '正常收货'), ('REWORK_RETURN', '返工回厂')], default='NORMAL', max_length=16)),
                ('received_at', models.DateField()),
                ('qualified_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('rework_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('scrap_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.processingbatch')),
                ('price_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.contractpriceversion')),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(default='DRAFT', max_length=12)),
                ('calc_hash', models.CharField(max_length=64)),
                ('confirmed_by_supplier', models.BooleanField(default=False)),
                ('confirmed_by_us', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='core.processingbatch')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_report_no', models.CharField(max_length=64, unique=True)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reported_at', models.DateField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_reports', to='core.processingbatch')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(max_length=16)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('note', models.CharField(blank=True, max_length=256)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deliverymilestone')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.receipt')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='QuantityLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(max_length=32)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('ref_type', models.CharField(max_length=32)),
                ('ref_id', models.PositiveBigIntegerField()),
                ('memo', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.processingbatch')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.item'),
        ),
        migrations.AddField(
            model_name='contract',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.item'),
        ),
        migrations.AddField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.supplier'),
        ),
    ]
